main:
  hosts:
    main-ubuntu:
      ansible_host: 54.179.255.113
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    second-ubuntu:
      ansible_host: 54.255.137.138
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
